// CATEGORIES
export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

// PHOTOS
export const ADD_PHOTOS = 'ADD_PHOTOS';
export const GET_PHOTOS = 'GET_PHOTOS';
export const GET_PHOTOS_FAIL = 'GET_PHOTOS_FAIL';
export const GET_PHOTOS_BY_CATEGORY = 'GET_PHOTOS_BY_CATEGORY';
export const GET_PHOTOS_BY_CATEGORY_SUCCESS = 'GET_PHOTOS_BY_CATEGORY_SUCCESS';

// CLIENT
export const ADD_CLIENT = 'ADD_CLIENT';
export const GET_CLIENT_LIST = 'GET_CLIENT_LIST';
export const GET_DASHBOARD_CLIENT_LIST = 'GET_DASHBOARD_CLIENT_LIST';
export const GET_CLIENT_LIST_SUCCESS = 'GET_CLIENT_LIST_SUCCESS';
export const GET_CLIENT_LIST_FAIL = 'GET_CLIENT_LIST_FAIL';
