export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';
export const ADD_PHOTOS = 'ADD_PHOTOS';
export const GET_PHOTOS = 'GET_PHOTOS';
export const GET_PHOTOS_FAIL = 'GET_PHOTOS_FAIL';
export const GET_PHOTOS_BY_CATEGORY = 'GET_PHOTOS_BY_CATEGORY';
export const GET_PHOTOS_BY_CATEGORY_SUCCESS = 'GET_PHOTOS_BY_CATEGORY_SUCCESS';
